<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="41546" started-at="2020-03-26T17:23:13Z" finished-at="2020-03-26T17:23:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="41546" started-at="2020-03-26T17:23:13Z" finished-at="2020-03-26T17:23:55Z">
      <class name="com.atc.seleniumframework.tests.Invalid_CreditCard_Num">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.atc.seleniumframework.tests.Invalid_CreditCard_Num@73ad2d6]" name="beforeSuite" is-config="true" duration-ms="25" started-at="2020-03-26T17:23:13Z" finished-at="2020-03-26T17:23:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest(java.lang.String)[pri:0, instance:com.atc.seleniumframework.tests.Invalid_CreditCard_Num@73ad2d6]" name="beforeTest" is-config="true" duration-ms="7030" started-at="2020-03-26T17:23:13Z" finished-at="2020-03-26T17:23:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="Invalid_CreditCard_Num()[pri:0, instance:com.atc.seleniumframework.tests.Invalid_CreditCard_Num@73ad2d6]" name="Invalid_CreditCard_Num" duration-ms="32674" started-at="2020-03-26T17:23:20Z" finished-at="2020-03-26T17:23:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4811 1111 1111 1113] but found [4811 1111 1111 1114]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4811 1111 1111 1113] but found [4811 1111 1111 1114]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotSame(Assert.java:772)
at org.testng.Assert.assertSame(Assert.java:723)
at org.testng.Assert.assertSame(Assert.java:733)
at com.atc.seleniumframework.pages.web.Web_PurchasePage.purchasepillow(Web_PurchasePage.java:109)
at com.atc.seleniumframework.tests.Invalid_CreditCard_Num.Invalid_CreditCard_Num(Invalid_CreditCard_Num.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Invalid_CreditCard_Num -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.atc.seleniumframework.tests.Invalid_CreditCard_Num@73ad2d6]" name="afterMethod" is-config="true" duration-ms="693" started-at="2020-03-26T17:23:53Z" finished-at="2020-03-26T17:23:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Invalid_CreditCard_Num status=FAILURE method=Invalid_CreditCard_Num.Invalid_CreditCard_Num()[pri:0, instance:com.atc.seleniumframework.tests.Invalid_CreditCard_Num@73ad2d6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.atc.seleniumframework.tests.Invalid_CreditCard_Num@73ad2d6]" name="afterTest" is-config="true" duration-ms="1121" started-at="2020-03-26T17:23:54Z" finished-at="2020-03-26T17:23:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.atc.seleniumframework.tests.Invalid_CreditCard_Num@73ad2d6]" name="afterSuite" is-config="true" duration-ms="672" started-at="2020-03-26T17:23:55Z" finished-at="2020-03-26T17:23:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.atc.seleniumframework.tests.Invalid_CreditCard_Num -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
